apiVersion: v1
kind: Namespace
metadata:
  name: password-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: password-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: password-manager
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
  namespace: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
        - name: app
          image: ayesha1777/password-manager-combined:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3000
              name: backend
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: DB_NAME
              value: passwordManager
            - name: MONGODB_URI
              value: mongodb://mongo:27017
            - name: FRONTEND_URL
              value: http://localhost
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: password-manager
  namespace: password-manager
spec:
  selector:
    app: password-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
